language: node_js
node_js:
  - 12
cache:
  directories:
    - node_modules
addons:
  chrome: stable
script:
  - npm run build
  - npm run test
  - lhci autorun --rc-overrides.upload.target=temporary-public-storage
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: client-secret.json
  project: nextshop-267916
  on: stable
  verbosity: debug
before_install:
  - openssl aes-256-cbc -K $encrypted_1cfc8d07e3c4_key -iv $encrypted_1cfc8d07e3c4_iv
    -in client-secret.json.enc -out client-secret.json -d
  - npm install -g @lhci/cli@0.4.x
